[package]
name = "derivatives"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colorous = "1.0.10"
eframe = "0.21.3"
egui = "0.21.0"
itertools = "0.10.5"
rand = "0.8.5"
